version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: asta_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asta_bd
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 15
  app:
    build: .
    container_name: asta_app
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/asta_bd?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysqldb:
        condition: service_healthy


volumes:
  mysql_data:
